packages:
  - "apps/*"
  - "infra"
  - "packages/*"

allowBuilds:
  "@fission-ai/openspec": true
  "@nestjs/core": false
  "@scarf/scarf": false
  "esbuild": true
  "sharp": true
  "unrs-resolver": true
